### ISSUE TITLE
Can you create those functions in C-programming language.

### ISSUE THREAD

**Issue by RsR-b** [rsr23/GitTutorial#3]
I'd love to see those in C lang.
Here is the language reference.
[C lang reference](https://en.cppreference.com/w/c/language)
# A sample code
```c
#include<stdio.h>
int main(void){
  printf("Hello, World!\n");
  return 0;
}
```
😃 
**Thank You**

**Comment by rsr23** [comment]
Sure, definitely.
Coming soon.
👍
